### ISSUE TITLE
Naming convensins

### ISSUE THREAD

**Issue by aberba** [libmir/dcv#23]
It seem your naming conventions and abbreviations does not give a good experience IMO. Long naming might be better in some cases.

Like;

``` d
Image image = imread("/path/to/image.png"); // read an image from filesystem.

auto slice = image.sliced; // slice image data (calls std.experimental.ndslice.slice.sliced on image data)

slice
    .asType!float[0..$, 0..$, 1] // convert slice data to float, and take the green channel only.
    .conv!symmetric(sobel!float(GradientDirection.DIR_X)) // convolve image with horizontal Sobel kernel.
    .byElement
    .ranged(0, 255).array.sliced(slice.shape[0..2]) // scale values to fit the range between the 0 and 255
    .imshow("Sobel derivatives"); // preview changes on screen.

waitKey();
```

some thing like `readImage(), showImage()`.

You tend to mix them, like there is `byElement()` which is not consistent with `imread(), imshow()` etc.

**Comment by ljubobratovicrelja** [comment]
`imread`/`imshow`/`imwrite` are function names already widely used for that purpose throughout most popular computer vision toolkits. Even if this naming is not consistent with the convention used by D community (and this library for that matter), I left those names so people who are familiar with any of those popular toolkits would easily find their way around, without consulting the API reference. And of course, since those names are used so much, I believe it would annoy people to name them otherwise.

So, those are exceptions purposefully named that way. Sorry, but I'd really like to keep it as is.

**Comment by aberba** [comment]
:ok:
